language: node_js
node_js:
- 9.8.0
env:
  global:
cache:
  directories:
  - node_modules
install:
- npm install bitballoon
- npm install
script:
- npm run build
deploy:
  provider: bitballoon
  site-id:
    secure: "mgsgVk7bFRtLt3anrdmlVBoRloea+bD1YzCzLDAfc0gj9WwhBkQGtr+/5Z5vixazHNwCSYSTUacVDAWEGQPnytHacP2+irp6pqn9qGOaIwsQpzay4DDQxZIbSHtatHcPY0xx/CEdumwIo2XKi0rNCJDQHkX/tD8PsErpsKVIHJYt49PDX9cjjMQb7h+T7USJDiRn8ySA+Eb9DYWVb4vbCdefvpZBNchD3Y8nng+SKGm5ohfgJUWDLrZ34cp9GMa+lRWVR4Pyl+7C9ECIdAOOdr1/7jkiL9sM/mhgJUGztwk9xki6nm3ZdYZWgJrGzRyWQ8ZSJ/+kYL7ni5XTjIqPZ6rclwX2q2RE8vQ9q5RATTe/LfvjhEOPc5geA1d7bhhACndvEyDT16weEbmj6CRIr0GjzBaTJ3VqbbvGTo+wNW9fIo/dJ9fr4bwfpo4FK2qNSZ1AUdQXPoqktXfU2Bajwu0kG7lvPUQQPf2ATNkrX0e2v40RmkPyowefkPWMkADBKmA/Zv9sG8l2uJqp91jDMZ2vRwKhAxUuM+gwCWvHroGoItiswfCiUGMfzYJ5EAV92cjrPaFAfo3WsZ8YhRIy1vTSNulKJfoChWI5EKaleG36es/5utuaN4b+b+4DBvga8W392WC9c2digtXCexIfyHq4mjRwxplMu7YGIcZh1vs="
  access-token:
    secure: "ruCKZ3ta2q3ska8KEjqwTpDRtt++VY/DOgtPPi43cizEhN12w4hJPd2/QIfoCEi+ZVTxGxISSFga6GB9z6xpjOb4YhnAUvJSPj5AioTleeZ3CPL5VGjCU4JD3mj3LFfls1hUX0SpgKW+U2BjHtt2BRNzii5mdQoJk/gA1qfHJTjQezsgygMyQe2eTUPYpGQGQW57hZjXHiJoiMDfF/40CkcDr16L0tzkEN3T2onHvLmekgp9+0QLH0r20t0dSkeI5aSdQ1D0KNblF7snQv2hrXI4pUj4bCj8sYwpvsBHjbA6L6XY8Q5m5brKm+1xbTN5SXRE6jrgw2lX7sJDSKZTze4N9Ghn7zNwKVpHB0jZGjJ+I9884jruCqj4jLOIudSf1rg0J9xkgPqcS37MtijoPd7YO3aVVYk8xapRySjbmUFAzbVsoN8rXDQL9lR5PpeAHlgGeYy3D9tdi3CssB0dWQJGlp4HAtEBmTSrMZFwEmp6Py3HC5CwDNo7UWNE1aFmVrc4XzsIqzEKZkN6WCS/xut7DZ2zLi3BYcV5NTI7YNiI0bYCgZrzznj0IiDtD7obGFpBU6zCJsKyztNPMAx73f2NcYq6jutbti7S1/wyjv3XS5kIfoYwJXRCcX6zmjFkEEh1CArqJ2gbC02pB7MgckullF5Z09aN6hNuQtfBmW4="
