language: node_js
node_js:
- 9.8.0
env:
  global:
  # BB_SITE_ID
  - secure: DTzEjs0n9eIZ6YmExa9Y/CGe90pfE0GcEbtTEICy+7mBqNcxCkhBMm4g7aovKeZq8d4iU43xNk0QoNZ4s78N3aAe46qh0l+nSap/iKN3oUA3G/ke5RsVhAjicFzT0oxvM20gc8Y8CXJQkH/2Zlz6MZKfRI8udrXKylW78PZOmFfBcqRJ/A8ifp/PRGCeg8H3ZGSQtenVADFVB5b4STvFPkPIwYuop8XlAUu9kQQ/I+bF8BYu6DRHm+S5fDLkm73vFE426q0aNfMknEcbpraNDztVgERWi9JhGKEmhEA0o6JZkLNuGW9mtCatkhqniwDemo/0f2x4AabPiRdX4VAVuvbqecCfcF+a0a9bAtX55FQbxa9kfubPu8WEnTOqndTl98CYkWAYvMBlupsR04rJqt0KOl47W4zfRRQSkiEnFrFL46XILki7nLKy7wx+wAiXhjmD6Piba46XxMqk1cIldt6RJz1lpZnHhaOpiChJVtbwiTW1QYwWLhUCXqIxfeX0t382dzlRmq1Szh3oq1EtPhseSEuLShkG7MJedGQI3W7rUm976h97jKB5DZrzxOlyXEyt0Gu/rLrXnqzEmi6dwpj0rLlAq4+7i7oInT81y0erpmUllf4HJctIsSGnvPD6qdywgngAhX8cLeVHSdwF74jXmaDYhQ1/RXMaxIqSiRw=

  # BB_CLIENT_ID
  - secure: jT0M2w8GkhPFF1uIEpu9LJj+eZeG+qdfDMzSlxrWuSXb65gzdY+z/leW+RQQnVU/y1dLb8MNk3AdaPgn7WFIbuZnjJ2aXMFeI3Un0D0hFvZKSrIG6KbdWnnSLCz8dNPsY5ZrW9RIuAb2CL6jyNYsJwN2s/Z0k5SBQpSd8H88JbTMmn7byUxqw+HRlUiT1O0NC3tj3KmjGrm3zDRBGCDWGz/Y1y9U4QFaCxPRojEOh7cn1YyD9ZrRckRnsUtvd6F6IDM2QvouNFdFjPVHClVPDkk0kz7rCBKlhD5IAfSoaEyb5NEjMoDPevGDpaQntAVlJ9H+CENbGdH6ZrvdHhz1t6x0324+34U4OHi1GBDU6nEiXoEcCoL9OZCik7v1NA8eRqcPi7ufB3J1UgLuqKo9iGv7Tu7/+Q7oTfzjqM4aTUBTwyebdHVRcFwAK7HbdndczdbKDjU3+sdL/HYf3KLvw6qMPYQMGamhDif3pviH5vVzFYeP8WL2W3rV0wgQXnDYXiM9owD4z1ZpFBwVM6WYvWUqOtK41u3G+I8Gq3VTDLMhc88TioFun3JNTy/hL0rkZ/CknHWFhMO9/liJ2OIEU787RV2rPfO9GqY11N9OLH+LmezrO8ydhTjF4vqpW66Q38/l3tNMnAv8qn78+XILZYLNI9n4CY8J3U3OMBY9Vg4=

  # BB_CLIENT_SECRET
  - secure: Yv4PzvCcH+iwbMjJuXxDD4q2KPvlA0SkNExfeUXwXsoBfE50DdhkDlU7zj+dDUTImVfnG0FWtVSnY1vn91RcRtHD4tgOWyKC7uDan0hhTHsbtZskUZqklyRthEvMx+N53uMqMCUhTzhPY5slKcUoLVhpO00UIOKwy8FJTvX1uELtFL77hwkiGZNWQvYDdFPycSuZEbwieWyedAahvNgXMdexAjKmfKNIJRCdXoVKmMP0ye7VWzbYgyzeFhvlW/0XDdZZhm3JNGFbYX+4xfy9NJqkNdrxuJdmkSkCgyd3wfGhqjWZWSBfA1YSEjFy1Idtjt8C42CN/BZAv+Xn4Jwgzrj8PIUc2QfdGMxZ0GuXF5fw7EoAym8mnfWcEhezeBRA06au+2KYoaeYTBRfIL2tb7KEgxvXu7pAHP+2sBopiIMRk7yJ1LRfx368k+AIm2IGXEgqrXppOD4HsSstJe/GDx1CQCwhqBLkW3xEbDzKJlwzpTpZlDORSG1OdS7gMw2MWnhvFtlI2UZQu5yY7SEFFxUVedmN60YYl0W0VlIkqch43PKdpko+A1QUrBjW8kTaIXxVSQofY89o5EEohBOYN/R+sz2hx9XQqCVU/bT6Su2UgzluX+LrhE6NsVX6dkQ0morahffIF7/p0EcdQ2qjcVzcDo0Sts9q5jJa4ROs/E8=

# Caching phrase.
cache:
  directories:
  - node_modules

# Dependency installation phrase.
install:
- npm install

# Build phrase
script:
- npm run build

# Custom deployment phrase.
after_success:
- node bitballoon.js --site-id=$BB_SITE_ID --client-id=$BB_CLIENT_ID --client-secret=$BB_CLIENT_SECRET
